name: Crawling Internet

on:
  repository_dispatch:
    types: ["Crawl"]

jobs:
  scrape:
    runs-on: ubuntu-latest
    concurrency:
      group: crawl

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: "npm"
      - name: Get secrets
        run: |
          echo ${{ secrets.BOT_TOKEN }} > ./bot_token
          echo ${{ secrets.SOURCE }} > ./source
      - name: Install v2ray
        run: |
          mkdir ./bin
          curl "https://github.com/v2fly/v2ray-core/releases/download/v5.1.0/v2ray-linux-64.zip" -L -o ./bin/v2ray.zip
          unzip ./bin/v2ray.zip -d ./bin/
          rm -rf ./bin/v2ray.zip
      - name: Start Crawling
        env:
          DATA: ${{ github.event.client_payload.message }}
        run: |
          npm install && npx tsc && node ./app/index.js $DATA
      - name: Add & Commit
        if: ${{ success() }}
        uses: EndBug/add-and-commit@v7.2.1
        with:
          add: '["./result", "./resources/database"]'
          default_author: github_actions
          fetch: false
          tag_push: "--force"
          message: "Update VPN"
