name: Crawling Internet

on:
  repository_dispatch:
    branches: "main"
    types: ["Crawl"]

jobs:
  scrape:
    runs-on: ubuntu-latest
    concurrency:
      group: crawl

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: "npm"
      - name: Get secrets
        run: |
          echo ${{ secrets.BOT_TOKEN }} > ./bot_token
      - name: Install binaries
        run: |
          mkdir ./bin
          curl "https://github.com/SagerNet/sing-box/releases/download/v1.1/sing-box-1.1-linux-amd64.tar.gz" -L -o ./bin/sing-box.tar.gz
          curl "https://github.com/xxf098/LiteSpeedTest/releases/download/v0.13.1/lite-linux-amd64-v0.13.1.gz" -L -o ./bin/lite.gz
          curl "https://github.com/tindy2013/subconverter/releases/download/v0.7.2/subconverter_linux64.tar.gz" -L -o ./bin/subconverter.tar.gz
          tar -xf ./bin/sing-box.tar.gz -C ./bin
          rm -rf ./bin/sing-box.tar.gz
          tar -xf ./bin/subconverter.tar.gz -C ./bin
          rm -rf ./bin/subconverter.tar.gz
          mv ./bin/sing-box-1.1-linux-amd64/* ./bin/
          gzip -dc < ./bin/lite.gz > ./bin/lite
          sudo chmod +x ./bin/*
      - name: Start Crawling
        env:
          DATA: ${{ github.event.client_payload.message }}
        run: |
          npm install && npx tsc && node ./app/index.js $DATA
      - name: Add & Commit
        if: ${{ success() }}
        uses: EndBug/add-and-commit@v9
        with:
          add: '["./result --force", "./resources/database --force"]'
          default_author: github_actions
          fetch: false
          tag_push: "--force"
          message: "Update VPN"
      - name: Scavenge next source
        if: ${{ always() }}
        run: |
          curl ${{ secrets.SOURCE }} -L
