name: Crawling Test

on:
  workflow_dispatch:
    branches: "dev"
jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: "npm"
      - name: Get secrets
        run: |
          echo 123456:ABC-DEF1234ghIkl-zyx57W2v1u123ew11 > ./bot_token
      - name: Install binaries
        run: |
          mkdir ./bin
          curl "https://github.com/SagerNet/sing-box/releases/download/v1.1/sing-box-1.1-linux-amd64.tar.gz" -L -o ./bin/sing-box.tar.gz
          curl "https://github.com/xxf098/LiteSpeedTest/releases/download/v0.13.1/lite-linux-amd64-v0.13.1.gz" -L -o ./bin/lite.gz
          curl "https://github.com/tindy2013/subconverter/releases/download/v0.7.2/subconverter_linux64.tar.gz" -L -o ./bin/subconverter.tar.gz
          tar -xf ./bin/sing-box.tar.gz -C ./bin
          rm -rf ./bin/sing-box.tar.gz
          tar -xf ./bin/subconverter.tar.gz -C ./bin
          rm -rf ./bin/subconverter.tar.gz
          mv ./bin/sing-box-1.1-linux-amd64/* ./bin/
          gzip -dc < ./bin/lite.gz > ./bin/lite
          sudo chmod +x ./bin/*
      - name: Start Crawling
        env:
          DATA: '{"url":"","filename":"1"}'
        run: |
          npm install && npx tsc && node ./app/index.js $DATA
